name: Deploy Frontend (OIDC)

on:
  push:
    branches: [ main, staging ]
    tags: [ 'v*' ]
  workflow_dispatch:
    inputs:
      dryrun:
        description: "Prévisualiser (ne rien écrire) ?"
        type: boolean
        default: true

permissions:
  id-token: write
  contents: read

env:
  REGION: eu-west-3
  BUCKET_STAGING: rcvo-transition
  BUCKET_PROD:    rcvo-officiel
  KEY_PREFIX: ui/   # on déploie sous ce sous-dossier

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ROLE_STAGING: arn:aws:iam::409818814260:role/RcvoDeployStagingRole
      ROLE_PROD:    arn:aws:iam::409818814260:role/RcvoDeployProdRole

    steps:
      - uses: actions/checkout@v4

      - name: Choisir rôle / bucket selon la ref
        id: pick
        run: |
          REF="${GITHUB_REF}"
          if [[ "$REF" == refs/heads/main || "$REF" == refs/tags/v* ]]; then
            echo "ROLE=${ROLE_PROD}"         >> "$GITHUB_OUTPUT"
            echo "BUCKET=${BUCKET_PROD}"     >> "$GITHUB_OUTPUT"
          else
            echo "ROLE=${ROLE_STAGING}"      >> "$GITHUB_OUTPUT"
            echo "BUCKET=${BUCKET_STAGING}"  >> "$GITHUB_OUTPUT"
          fi

      - name: Configurer AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.REGION }}
          role-to-assume: ${{ steps.pick.outputs.ROLE }}

      # npm ci uniquement si package.json ET package-lock.json existent
      - name: Installer deps (si lockfile)
        if: ${{ hashFiles('package.json') != '' && hashFiles('package-lock.json') != '' }}
        run: npm ci

      # build uniquement si package.json contient un script "build"
      - name: Build (si script présent)
        if: ${{ hashFiles('package.json') != '' }}
        run: |
          if jq -e '.scripts.build' package.json >/dev/null 2>&1; then
            npm run build
          else
            echo "Pas de script build -> on publiera tel quel"
          fi

      - name: Localiser le dossier à publier
        id: dist
        run: |
          set -e
          for D in dist build public out .; do
            if [ -d "$D" ]; then
              echo "dir=$D" >> "$GITHUB_OUTPUT"
              echo "Publier: $D"
              exit 0
            fi
          done
          # Si aucun des dossiers ci-dessus n'existe, on publiera la racine
          echo "dir=." >> "$GITHUB_OUTPUT"
          echo "Publier: ."

      - name: Prévisualisation (DRY-RUN)
        if: ${{ inputs.dryrun }}
        run: |
          echo "DRY-RUN -> n'écrit rien"
          aws s3 sync "${{ steps.dist.outputs.dir }}/" "s3://${{ steps.pick.outputs.BUCKET }}/${{ env.KEY_PREFIX }}" \
            --only-show-errors --exact-timestamps --dryrun

      - name: Sync vers S3 (écriture réelle)
        if: ${{ !inputs.dryrun }}
        run: |
          aws s3 sync "${{ steps.dist.outputs.dir }}/" "s3://${{ steps.pick.outputs.BUCKET }}/${{ env.KEY_PREFIX }}" \
            --only-show-errors --exact-timestamps
          echo "Déployé vers s3://${{ steps.pick.outputs.BUCKET }}/${{ env.KEY_PREFIX }}"

      # Invalidation CloudFront (désactivée tant qu'on n'a pas d'ID confirmé)
      # - name: Invalidation CloudFront
      #   run: aws cloudfront create-invalidation --distribution-id DXXXXXXXX --paths "/*"

      - name: Smoke test (statique)
        if: ${{ !inputs.dryrun }}
        run: aws s3 ls "s3://${{ steps.pick.outputs.BUCKET }}/${{ env.KEY_PREFIX }}" | head -n 20
