name: Déployer l'interface Rcvo (UI) sur Elastic Beanstalk

on:
  workflow_dispatch:
    inputs:
      version_label:
        description: "Version à déployer (facultatif)"
        required: false

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-3
  EB_ENV_NAME: Rcvo-UI-prod                  # <— très important
  EB_APP_NAME: Rcvo-UI
  S3_BUCKET: elasticbeanstalk-eu-west-3-409818814260

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configurer AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/checkout@v4

      - name: Préparer le package de déploiement
        run: |
          set -euo pipefail
          mkdir -p bundle
          zip -qr bundle/ui.zip .platform || true
          if [ -d "build" ]; then zip -qr bundle/ui.zip build; fi
          if [ -d "dist" ];  then zip -qr bundle/ui.zip dist;  fi

      - name: Envoyer sur S3 et créer une nouvelle version EB
        run: |
          set -euo pipefail
          LABEL="${{ inputs.version_label }}"
          [ -z "$LABEL" ] && LABEL="ui-$(date +%Y%m%d-%H%M%S)"
          aws s3 cp bundle/ui.zip "s3://${{ env.S3_BUCKET }}/${{ env.EB_APP_NAME }}/$LABEL.zip"
          aws elasticbeanstalk create-application-version \
            --application-name "$EB_APP_NAME" \
            --version-label "$LABEL" \
            --source-bundle S3Bucket="${{ env.S3_BUCKET }}",S3Key="${{ env.EB_APP_NAME }}/$LABEL.zip"
          echo "LABEL=$LABEL" >> $GITHUB_ENV

      - name: Vérifier l’environnement cible
        run: |
          aws elasticbeanstalk describe-environments \
            --environment-names "$EB_ENV_NAME" \
            --query 'Environments[0].EnvironmentName' --output text

      - name: Déployer sur Elastic Beanstalk
        run: |
          set -euo pipefail
          echo "Déploiement de la version $LABEL sur $EB_ENV_NAME..."
          aws elasticbeanstalk update-environment \
            --environment-name "$EB_ENV_NAME" \
            --version-label "$LABEL"
